apiVersion: v1
kind: Secret
metadata: 
    name: mysql-secret
type: Opaque
data: 
    mysql-admin-password: Q2xhcnVzd2F5XzE=
    mysql-root-password: UDEyMzQ1NnA=



# Clarusway_1 ve R1234r şifreleri önce encode edilmeli bunun için
#echo -n 'P123456p' | base64   --->  mysql-root-password olarak mysql-secret.yaml dostasında adreslenir
#echo -n 'CLarusway_1' | base64 ----> mysql-admin-password olarak mysql-secret.yaml dostasında adreslenir

# Clarusway_1 ve P123456p şifreleri decode etmek için
# echo -n 'UDEyMzQ1NnA=' | base64 --decode     ---> It gives root us poassword
# echo -n 'Q2xhcnVzd2F5XzE=' | base64 --decode   ---> It gives us admin password