apiVersion: v1
kind: Service
metadata:
  name: app-api-service
  labels:
    name: app-api-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
  selector:
    name: app-api-pod
